/**
 * ServiceBusManagementClient
 * Azure Service Bus client
 *
 * The version of the OpenAPI document: 2017-04-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.speedfl.operator.azure.servicebus.queues.model;


import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;


/**
  * Message Count Details.
 **/


@Getter
@Setter
@EqualsAndHashCode
@ToString
@JsonInclude(Include.NON_NULL)
public class MessageCountDetails  {
  
 /**
   * Number of active messages in the queue, topic, or subscription.
  **/
  @JsonProperty("activeMessageCount")
  private Long activeMessageCount;

 /**
   * Number of messages that are dead lettered.
  **/
  @JsonProperty("deadLetterMessageCount")
  private Long deadLetterMessageCount;

 /**
   * Number of scheduled messages.
  **/
  @JsonProperty("scheduledMessageCount")
  private Long scheduledMessageCount;

 /**
   * Number of messages transferred to another queue, topic, or subscription.
  **/
  @JsonProperty("transferMessageCount")
  private Long transferMessageCount;

 /**
   * Number of messages transferred into dead letters.
  **/
  @JsonProperty("transferDeadLetterMessageCount")
  private Long transferDeadLetterMessageCount;
}

