/**
 * ServiceBusManagementClient
 * Azure Service Bus client
 *
 * The version of the OpenAPI document: 2017-04-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.speedfl.operator.azure.servicebus.queues.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;


/**
  * Description of queue Resource.
 **/


@Getter
@Setter
@EqualsAndHashCode
@ToString
@JsonInclude(Include.NON_NULL)
public class SBQueue  {
  
  @JsonProperty("properties")
  private SBQueueProperties properties;

 /**
   * Resource Id
  **/
  @JsonProperty("id")
  private String id;

 /**
   * Resource name
  **/
  @JsonProperty("name")
  private String name;

 /**
   * Resource type
  **/
  @JsonProperty("type")
  private String type;
}

