---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-deployment" .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | quote }}
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/part-of: {{ .Chart.Version | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name | quote }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | quote }}
        app.kubernetes.io/name: {{ .Chart.Name | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/managed-by: "Helm"
        app.kubernetes.io/part-of: {{ .Chart.Version | quote }}
        app.kubernetes.io/component: "Deployment"
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AZURE_OPERATOR_LOCATION
              value: {{ .Values.region | quote }}
            - name: AZURE_OPERATOR_TENANT_ID
              valueFrom:
                secretKeyRef:
                  key: tenant-id
                  name: azure-resource-operator-secret
            - name: AZURE_OPERATOR_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: client-id
                  name: azure-resource-operator-secret
            - name: AZURE_OPERATOR_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: client-secret
                  name: azure-resource-operator-secret
            - name: AZURE_OPERATOR_SUBSCRIPTION_ID
              valueFrom:
                secretKeyRef:
                  key: subscription-id
                  name: azure-resource-operator-secret
          {{- if .Values.image.registry }}
          image: {{ printf "%s/%s" .Values.image.registry .Values.image.name | quote }}
          {{- else }}
          image: {{ .Values.image.name | quote }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: azure-resource-operator
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 64Mi
      serviceAccount: {{ printf "%s-sa" .Release.Name | quote }}