/**
 * ServiceBusManagementClient
 * Azure Service Bus client
 *
 * The version of the OpenAPI document: 2017-04-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.speedfl.operator.azure.resources.resourcegroups.model;



import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Entity status.
 */
public enum EntityStatus {
  
  @JsonProperty("Active")ACTIVE("Active"),
  
  @JsonProperty("Disabled")DISABLED("Disabled"),
  
  @JsonProperty("Restoring")RESTORING("Restoring"),
  
  @JsonProperty("SendDisabled")SENDDISABLED("SendDisabled"),
  
  @JsonProperty("ReceiveDisabled")RECEIVEDISABLED("ReceiveDisabled"),
  
  @JsonProperty("Creating")CREATING("Creating"),
  
  @JsonProperty("Deleting")DELETING("Deleting"),
  
  @JsonProperty("Renaming")RENAMING("Renaming"),
  
  @JsonProperty("Unknown")UNKNOWN("Unknown");

  private String value;

  EntityStatus(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EntityStatus fromValue(String text) {
    for (EntityStatus b : EntityStatus.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + text + "'");
  }
}

