/**
 * ResourceManagementClient
 * Provides operations for working with resources and resource groups.
 *
 * The version of the OpenAPI document: 2021-04-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.speedfl.operator.azure.resources.resourcegroups.model;

import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;


/**
  * Resource group information.
 **/


@Getter
@Setter
@EqualsAndHashCode
@ToString
@JsonInclude(Include.NON_NULL)
public class ResourceGroup  {
  
 /**
   * The ID of the resource group.
  **/
  @JsonProperty("id")
  private String id;

 /**
   * The name of the resource group.
  **/
  @JsonProperty("name")
  private String name;

 /**
   * The type of the resource group.
  **/
  @JsonProperty("type")
  private String type;

  @JsonProperty("properties")
  private ResourceGroupProperties properties;

 /**
   * The location of the resource group. It cannot be changed after the resource group has been created. It must be one of the supported Azure locations.
  **/
  @JsonProperty("location")
  private String location;

 /**
   * The ID of the resource that manages this resource group.
  **/
  @JsonProperty("managedBy")
  private String managedBy;

 /**
   * The tags attached to the resource group.
  **/
  @JsonProperty("tags")
  private Map<String, String> tags = null;
}

