/**
 * ServiceBusManagementClient
 * Azure Service Bus client
 *
 * The version of the OpenAPI document: 2017-04-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.speedfl.operator.azure.servicebus.namespaces.model;

import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;


/**
  * Description of a namespace resource.
 **/


@Getter
@Setter
@EqualsAndHashCode
@ToString
@JsonInclude(Include.NON_NULL)
public class SBNamespace  {
  
  @JsonProperty("sku")
  private SBSku sku;

  @JsonProperty("properties")
  private SBNamespaceProperties properties;

 /**
   * Resource Id
  **/
  @JsonProperty("id")
  private String id;

 /**
   * Resource name
  **/
  @JsonProperty("name")
  private String name;

 /**
   * Resource type
  **/
  @JsonProperty("type")
  private String type;
  
  /**
   * All below manually fixed:
   * https://github.com/OpenAPITools/openapi-generator/issues/10638
  **/
  
  /**
   * Resource location
  **/
  @JsonProperty("location")
  private String location;
  
  /**
   * Resource location
  **/
  @JsonProperty("tags")
  private Map<String, String> tags = null;
}

