/**
 * ServiceBusManagementClient
 * Azure Service Bus client
 *
 * The version of the OpenAPI document: 2017-04-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.speedfl.operator.azure.servicebus.namespaces.model;


import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;


/**
  * SKU of the namespace.
 **/


@Getter
@Setter
@EqualsAndHashCode
@ToString
@JsonInclude(Include.NON_NULL)
public class SBSku  {
  
  public enum NameEnum {

    @JsonProperty("Basic")BASIC(String.valueOf("Basic")), @JsonProperty("Standard")STANDARD(String.valueOf("Standard")), @JsonProperty("Premium")PREMIUM(String.valueOf("Premium"));    


    String value;

    NameEnum (String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

  }

 /**
   * Name of this SKU.
  **/
  @JsonProperty("name")
  private NameEnum name;

  public enum TierEnum {

    @JsonProperty("Basic")BASIC(String.valueOf("Basic")), @JsonProperty("Standard")STANDARD(String.valueOf("Standard")), @JsonProperty("Premium")PREMIUM(String.valueOf("Premium"));    


    String value;

    TierEnum (String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

  }

 /**
   * The billing tier of this particular SKU.
  **/
  @JsonProperty("tier")
  private TierEnum tier;

 /**
   * The specified messaging units for the tier. For Premium tier, capacity are 1,2 and 4.
  **/
  @JsonProperty("capacity")
  private Integer capacity;
}

